version: "3.8"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: discord_tmio
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - database:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "--host=localhost", "--user=root", "--password=${DB_PASS}"]
      timeout: 20s
      retries: 10
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "discord-tmio"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER_ID: ${OWNER_ID}
      TMIO_API: ${TMIO_API}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ${DB_PASS}
      DB_NAME: discord_tmio

volumes:
  database:
    driver: local
