version: "3.9"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: discord-tmio
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - database:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "--host=localhost", "--user=root", "--password=${DB_PASS}"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7000:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      #PMA_USER: root
      #PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

  discord:
    image: node:lts
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER_ID: ${OWNER_ID}
      TMIO_API: ${TMIO_API}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ${DB_PASS}
      DB_NAME: discord-tmio
      NODE_ENV: production
    command: node ./src/index.js

volumes:
  database:
    driver: local
