# docker compose file for mysql server in dev, you always need node locally
version: "3.9"
services:
  sql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    command: --authentication_policy=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=sql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASS}
      - PMA_PORT=${DB_PORT}
    ports:
      - 81:80