name: Deploy to Hosted server
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: Techie-Pi/node-vps-deployment@main
        with:
          remote-path: ${{ secrets.SERVER_PATH }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.SERVER_PASS }}
          pm2-id: "pm2.config.js"